<?php

declare(strict_types=1);

/**
 * Convert school.sql INSERT data into smartschool.sql-compatible INSERT statements.
 *
 * Usage:
 *   php convert_school_to_smartschool.php [old_sql] [new_sql] [output_sql] [report_txt]
 */

$oldSql = $argv[1] ?? 'school.sql';
$newSql = $argv[2] ?? 'smartschool.sql';
$outSql = $argv[3] ?? 'school_to_smartschool_data.sql';
$reportFile = $argv[4] ?? 'school_to_smartschool_report.txt';

if (!is_file($oldSql)) {
    fwrite(STDERR, "Old SQL file not found: {$oldSql}\n");
    exit(1);
}
if (!is_file($newSql)) {
    fwrite(STDERR, "New SQL file not found: {$newSql}\n");
    exit(1);
}

$oldSchema = parseSchema($oldSql);
$newSchema = parseSchema($newSql);

$outHandle = fopen($outSql, 'wb');
if (!$outHandle) {
    fwrite(STDERR, "Unable to create output file: {$outSql}\n");
    exit(1);
}

$report = [
    'tables_old' => count($oldSchema),
    'tables_new' => count($newSchema),
    'shared_tables' => count(array_intersect(array_keys($oldSchema), array_keys($newSchema))),
    'insert_statements_total' => 0,
    'insert_statements_converted' => 0,
    'insert_rows_total' => 0,
    'insert_rows_converted' => 0,
    'tables_converted' => [],
    'tables_skipped' => [],
    'parse_errors' => [],
];

fwrite($outHandle, "-- Generated by convert_school_to_smartschool.php\n");
fwrite($outHandle, "-- Source old dump: {$oldSql}\n");
fwrite($outHandle, "-- Target schema: {$newSql}\n");
fwrite($outHandle, '-- Generated at: ' . date('Y-m-d H:i:s') . "\n\n");
fwrite($outHandle, "SET FOREIGN_KEY_CHECKS = 0;\n\n");

$insertHandle = fopen($oldSql, 'rb');
if (!$insertHandle) {
    fclose($outHandle);
    fwrite(STDERR, "Unable to read old SQL file: {$oldSql}\n");
    exit(1);
}

$capturing = false;
$statement = '';
$lineNo = 0;

while (($line = fgets($insertHandle)) !== false) {
    $lineNo++;
    $trim = ltrim($line);

    if (!$capturing) {
        if (stripos($trim, 'INSERT INTO ') === 0) {
            $capturing = true;
            $statement = $line;
            if (statementEnds($statement)) {
                processInsertStatement($statement, $lineNo, $newSchema, $outHandle, $report);
                $capturing = false;
                $statement = '';
            }
        }
        continue;
    }

    $statement .= $line;
    if (statementEnds($statement)) {
        processInsertStatement($statement, $lineNo, $newSchema, $outHandle, $report);
        $capturing = false;
        $statement = '';
    }
}

if ($capturing && trim($statement) !== '') {
    $report['parse_errors'][] = "Unterminated INSERT near line {$lineNo}";
}

fclose($insertHandle);

fwrite($outHandle, "\nSET FOREIGN_KEY_CHECKS = 1;\n");
fclose($outHandle);

ksort($report['tables_converted']);
ksort($report['tables_skipped']);

$reportText = [];
$reportText[] = "School -> SmartSchool Data Conversion Report";
$reportText[] = str_repeat('=', 46);
$reportText[] = "Old schema tables: {$report['tables_old']}";
$reportText[] = "New schema tables: {$report['tables_new']}";
$reportText[] = "Shared tables: {$report['shared_tables']}";
$reportText[] = "";
$reportText[] = "INSERT statements found: {$report['insert_statements_total']}";
$reportText[] = "INSERT statements converted: {$report['insert_statements_converted']}";
$reportText[] = "Rows found in INSERTs: {$report['insert_rows_total']}";
$reportText[] = "Rows written to output: {$report['insert_rows_converted']}";
$reportText[] = "";
$reportText[] = "Converted tables: " . count($report['tables_converted']);
foreach ($report['tables_converted'] as $table => $count) {
    $reportText[] = "  - {$table}: {$count} statements";
}
$reportText[] = "";
$reportText[] = "Skipped tables: " . count($report['tables_skipped']);
foreach ($report['tables_skipped'] as $table => $reasons) {
    $reportText[] = "  - {$table}: " . implode('; ', array_keys($reasons));
}
$reportText[] = "";
$reportText[] = "Parse errors: " . count($report['parse_errors']);
foreach ($report['parse_errors'] as $err) {
    $reportText[] = "  - {$err}";
}

file_put_contents($reportFile, implode(PHP_EOL, $reportText) . PHP_EOL);

fwrite(STDOUT, "Conversion complete.\n");
fwrite(STDOUT, "Output SQL: {$outSql}\n");
fwrite(STDOUT, "Report: {$reportFile}\n");

function parseSchema(string $file): array
{
    $tables = [];
    $handle = fopen($file, 'rb');
    if (!$handle) {
        throw new RuntimeException("Unable to open schema file: {$file}");
    }

    $current = null;

    while (($line = fgets($handle)) !== false) {
        $trim = trim($line);

        if ($current === null) {
            if (preg_match('/^CREATE TABLE `([^`]+)` \($/i', $trim, $m)) {
                $current = [
                    'name' => $m[1],
                    'columns' => [],
                    'meta' => [],
                ];
            }
            continue;
        }

        if (preg_match('/^\) ENGINE=/i', $trim)) {
            $tables[$current['name']] = [
                'columns' => $current['columns'],
                'meta' => $current['meta'],
            ];
            $current = null;
            continue;
        }

        if (!preg_match('/^`([^`]+)`\s+(.+?)(,)?$/', $trim, $m)) {
            continue;
        }

        $column = $m[1];
        $definition = trim($m[2]);
        $upper = strtoupper($definition);

        $type = '';
        if (preg_match('/^([a-zA-Z]+)/', $definition, $typeMatch)) {
            $type = strtolower($typeMatch[1]);
        }

        $current['columns'][] = $column;
        $current['meta'][$column] = [
            'raw' => $definition,
            'type' => $type,
            'not_null' => strpos($upper, 'NOT NULL') !== false,
            'has_default' => strpos($upper, 'DEFAULT') !== false,
            'auto_increment' => strpos($upper, 'AUTO_INCREMENT') !== false,
        ];
    }

    fclose($handle);
    return $tables;
}

function statementEnds(string $statement): bool
{
    return (bool) preg_match('/;\s*$/s', $statement);
}

function processInsertStatement(string $statement, int $lineNo, array $newSchema, $outHandle, array &$report): void
{
    $report['insert_statements_total']++;

    if (!preg_match('/^\s*INSERT\s+INTO\s+`([^`]+)`\s*\((.*?)\)\s*VALUES\s*(.*);\s*$/is', $statement, $m)) {
        $report['parse_errors'][] = "Unparsed INSERT at line {$lineNo}";
        return;
    }

    $table = $m[1];
    $columnSql = $m[2];
    $valuesSql = trim($m[3]);

    if (!isset($newSchema[$table])) {
        markSkipped($report, $table, 'table_missing_in_new_schema');
        return;
    }

    preg_match_all('/`([^`]+)`/', $columnSql, $colsMatch);
    $oldColumns = $colsMatch[1];

    if ($oldColumns === []) {
        markSkipped($report, $table, 'no_columns_in_insert');
        return;
    }

    $newColumns = $newSchema[$table]['columns'];
    $newMeta = $newSchema[$table]['meta'];
    $oldIndex = array_flip($oldColumns);

    $targetColumns = [];
    $selectors = [];

    foreach ($newColumns as $col) {
        if (isset($oldIndex[$col])) {
            $targetColumns[] = $col;
            $selectors[] = ['kind' => 'source', 'index' => $oldIndex[$col]];
            continue;
        }

        $meta = $newMeta[$col];
        if (!isRequiredWithoutDefault($meta)) {
            continue;
        }

        $fallback = fallbackSqlValue($table, $col, $meta);
        if ($fallback === null) {
            markSkipped($report, $table, "missing_required_column:{$col}");
            return;
        }

        $targetColumns[] = $col;
        $selectors[] = ['kind' => 'fixed', 'value' => $fallback];
    }

    if ($targetColumns === []) {
        markSkipped($report, $table, 'no_mappable_columns');
        return;
    }

    $tuples = splitTuples($valuesSql);
    if ($tuples === null) {
        markSkipped($report, $table, 'tuple_parse_failed');
        $report['parse_errors'][] = "Tuple parse failed for {$table} near line {$lineNo}";
        return;
    }

    if ($tuples === []) {
        markSkipped($report, $table, 'no_rows_in_values');
        return;
    }

    $report['insert_rows_total'] += count($tuples);

    $outRows = [];
    foreach ($tuples as $tuple) {
        $fields = splitFields($tuple);
        if ($fields === null) {
            markSkipped($report, $table, 'field_parse_failed');
            $report['parse_errors'][] = "Field parse failed for {$table} near line {$lineNo}";
            return;
        }

        if (count($fields) !== count($oldColumns)) {
            markSkipped($report, $table, 'column_count_mismatch');
            $report['parse_errors'][] = "Column/value mismatch for {$table} near line {$lineNo}; cols=" . count($oldColumns) . " values=" . count($fields);
            return;
        }

        $outFields = [];
        foreach ($selectors as $selector) {
            if ($selector['kind'] === 'source') {
                $outFields[] = $fields[$selector['index']];
            } else {
                $outFields[] = $selector['value'];
            }
        }
        $outRows[] = '(' . implode(', ', $outFields) . ')';
    }

    $quotedCols = array_map(static fn($c) => "`{$c}`", $targetColumns);
    fwrite($outHandle, "INSERT INTO `{$table}` (" . implode(', ', $quotedCols) . ") VALUES\n");
    fwrite($outHandle, implode(",\n", $outRows));
    fwrite($outHandle, ";\n\n");

    $report['insert_statements_converted']++;
    $report['insert_rows_converted'] += count($outRows);
    if (!isset($report['tables_converted'][$table])) {
        $report['tables_converted'][$table] = 0;
    }
    $report['tables_converted'][$table]++;
}

function isRequiredWithoutDefault(array $meta): bool
{
    return $meta['not_null'] && !$meta['has_default'] && !$meta['auto_increment'];
}

function fallbackSqlValue(string $table, string $column, array $meta): ?string
{
    // Explicit table/column overrides for known schema differences.
    $specific = [
        'fee_groups.nature' => "'income'",
        'feetype.nature' => "'income'",
        'id_card.enable_student_rollno' => '0',
        'notification_setting.whatsapp_template_id' => "''",
        'sch_settings.fees_discount' => '0',
        'sch_settings.student_delete_chat' => '0',
        'sch_settings.guardian_delete_chat' => '0',
        'sch_settings.staff_delete_chat' => '0',
        'sch_settings.theme_font_color' => "''",
        'sch_settings.student_form_multi_class' => "''",
        'sidebar_menus.product_name' => "''",
        'users.login_token' => "''",
    ];

    $key = $table . '.' . $column;
    if (isset($specific[$key])) {
        return $specific[$key];
    }

    $type = $meta['type'];
    if (in_array($type, ['tinyint', 'smallint', 'mediumint', 'int', 'bigint', 'decimal', 'float', 'double', 'bit'], true)) {
        return '0';
    }

    if (in_array($type, ['date'], true)) {
        return "'1970-01-01'";
    }

    if (in_array($type, ['datetime', 'timestamp'], true)) {
        return "'1970-01-01 00:00:00'";
    }

    if (in_array($type, ['time'], true)) {
        return "'00:00:00'";
    }

    if (in_array($type, ['year'], true)) {
        return "'1970'";
    }

    if (in_array($type, ['char', 'varchar', 'text', 'tinytext', 'mediumtext', 'longtext', 'enum', 'set'], true)) {
        return "''";
    }

    return null;
}

function splitTuples(string $valuesSql): ?array
{
    $len = strlen($valuesSql);
    $tuples = [];
    $inString = false;
    $depth = 0;
    $escape = false;
    $start = null;

    for ($i = 0; $i < $len; $i++) {
        $ch = $valuesSql[$i];

        if ($inString) {
            if ($escape) {
                $escape = false;
                continue;
            }

            if ($ch === '\\') {
                $escape = true;
                continue;
            }

            if ($ch === "'") {
                if ($i + 1 < $len && $valuesSql[$i + 1] === "'") {
                    $i++;
                    continue;
                }
                $inString = false;
            }
            continue;
        }

        if ($ch === "'") {
            $inString = true;
            continue;
        }

        if ($ch === '(') {
            if ($depth === 0) {
                $start = $i;
            }
            $depth++;
            continue;
        }

        if ($ch === ')') {
            $depth--;
            if ($depth < 0) {
                return null;
            }
            if ($depth === 0 && $start !== null) {
                $tuples[] = trim(substr($valuesSql, $start, $i - $start + 1));
                $start = null;
            }
        }
    }

    if ($inString || $depth !== 0) {
        return null;
    }

    return $tuples;
}

function splitFields(string $tuple): ?array
{
    $tuple = trim($tuple);
    if ($tuple === '' || $tuple[0] !== '(' || substr($tuple, -1) !== ')') {
        return null;
    }

    $inner = substr($tuple, 1, -1);
    $len = strlen($inner);
    $fields = [];
    $buf = '';
    $inString = false;
    $escape = false;
    $depth = 0;

    for ($i = 0; $i < $len; $i++) {
        $ch = $inner[$i];

        if ($inString) {
            $buf .= $ch;
            if ($escape) {
                $escape = false;
                continue;
            }
            if ($ch === '\\') {
                $escape = true;
                continue;
            }
            if ($ch === "'") {
                if ($i + 1 < $len && $inner[$i + 1] === "'") {
                    $buf .= "'";
                    $i++;
                    continue;
                }
                $inString = false;
            }
            continue;
        }

        if ($ch === "'") {
            $inString = true;
            $buf .= $ch;
            continue;
        }

        if ($ch === '(') {
            $depth++;
            $buf .= $ch;
            continue;
        }

        if ($ch === ')') {
            if ($depth > 0) {
                $depth--;
            }
            $buf .= $ch;
            continue;
        }

        if ($ch === ',' && $depth === 0) {
            $fields[] = trim($buf);
            $buf = '';
            continue;
        }

        $buf .= $ch;
    }

    if ($inString || $depth !== 0) {
        return null;
    }

    $fields[] = trim($buf);
    return $fields;
}

function markSkipped(array &$report, string $table, string $reason): void
{
    if (!isset($report['tables_skipped'][$table])) {
        $report['tables_skipped'][$table] = [];
    }
    if (!isset($report['tables_skipped'][$table][$reason])) {
        $report['tables_skipped'][$table][$reason] = 0;
    }
    $report['tables_skipped'][$table][$reason]++;
}
